"""testing

Revision ID: 0e3ed8014d32
Revises: 286ea75f633c
Create Date: 2021-03-13 09:08:27.971620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e3ed8014d32'
down_revision = '286ea75f633c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    op.drop_table('image_metadata')
    op.drop_table('similar_images')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('similar_images',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('similar_image_path_short', sa.VARCHAR(length=120), nullable=True),
    sa.Column('similar_image_path_full', sa.VARCHAR(length=120), nullable=True),
    sa.Column('base_image_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['base_image_id'], ['image_metadata.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('similar_image_path_full'),
    sa.UniqueConstraint('similar_image_path_short')
    )
    op.create_table('image_metadata',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('image', sa.VARCHAR(length=120), nullable=True),
    sa.Column('brand', sa.VARCHAR(length=120), nullable=True),
    sa.Column('description', sa.VARCHAR(length=120), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.Column('image_path_short', sa.VARCHAR(length=120), nullable=True),
    sa.Column('clothing', sa.VARCHAR(length=120), nullable=True),
    sa.Column('material', sa.VARCHAR(length=120), nullable=True),
    sa.Column('pattern', sa.VARCHAR(length=120), nullable=True),
    sa.Column('fit', sa.VARCHAR(length=120), nullable=True),
    sa.Column('style', sa.VARCHAR(length=120), nullable=True),
    sa.Column('image_path_full', sa.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image'),
    sa.UniqueConstraint('image_path_full')
    )
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
