"""SimilarImages table

Revision ID: 286ea75f633c
Revises: 9dc19845e25a
Create Date: 2021-03-13 08:34:12.347137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '286ea75f633c'
down_revision = '9dc19845e25a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('similar_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('similar_image_path_short', sa.String(length=120), nullable=True),
    sa.Column('similar_image_path_full', sa.String(length=120), nullable=True),
    sa.Column('base_image_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['base_image_id'], ['image_metadata.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('similar_image_path_full'),
    sa.UniqueConstraint('similar_image_path_short')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('similar_images')
    # ### end Alembic commands ###
