"""ImageMetadata table

Revision ID: 9dc19845e25a
Revises: 
Create Date: 2021-03-13 08:00:40.166793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dc19845e25a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=120), nullable=True),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('price', sa.Float(precision=64), nullable=True),
    sa.Column('image_path_short', sa.String(length=120), nullable=True),
    sa.Column('clothing', sa.String(length=120), nullable=True),
    sa.Column('material', sa.String(length=120), nullable=True),
    sa.Column('pattern', sa.String(length=120), nullable=True),
    sa.Column('fit', sa.String(length=120), nullable=True),
    sa.Column('style', sa.String(length=120), nullable=True),
    sa.Column('image_path_full', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image'),
    sa.UniqueConstraint('image_path_full')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_metadata')
    # ### end Alembic commands ###
