"""testing

Revision ID: cd23b441fa1d
Revises: ade245cd1b97
Create Date: 2021-03-13 09:15:34.937167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd23b441fa1d'
down_revision = 'ade245cd1b97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_metadata', sa.Column('brand', sa.String(length=120), nullable=True))
    op.add_column('image_metadata', sa.Column('clothing', sa.String(length=120), nullable=True))
    op.add_column('image_metadata', sa.Column('description', sa.String(length=120), nullable=True))
    op.add_column('image_metadata', sa.Column('fit', sa.String(length=120), nullable=True))
    op.add_column('image_metadata', sa.Column('image', sa.String(length=120), nullable=True))
    op.add_column('image_metadata', sa.Column('image_path_full', sa.String(length=120), nullable=True))
    op.add_column('image_metadata', sa.Column('image_path_short', sa.String(length=120), nullable=True))
    op.add_column('image_metadata', sa.Column('material', sa.String(length=120), nullable=True))
    op.add_column('image_metadata', sa.Column('pattern', sa.String(length=120), nullable=True))
    op.add_column('image_metadata', sa.Column('price', sa.Float(precision=64), nullable=True))
    op.add_column('image_metadata', sa.Column('style', sa.String(length=120), nullable=True))
    op.drop_index('ix_image_metadata_email', table_name='image_metadata')
    op.drop_index('ix_image_metadata_username', table_name='image_metadata')
    op.create_unique_constraint(None, 'image_metadata', ['image_path_full'])
    op.create_unique_constraint(None, 'image_metadata', ['image'])
    op.drop_column('image_metadata', 'password_hash')
    op.drop_column('image_metadata', 'username')
    op.drop_column('image_metadata', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_metadata', sa.Column('email', sa.VARCHAR(length=120), nullable=True))
    op.add_column('image_metadata', sa.Column('username', sa.VARCHAR(length=64), nullable=True))
    op.add_column('image_metadata', sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
    op.drop_constraint(None, 'image_metadata', type_='unique')
    op.drop_constraint(None, 'image_metadata', type_='unique')
    op.create_index('ix_image_metadata_username', 'image_metadata', ['username'], unique=1)
    op.create_index('ix_image_metadata_email', 'image_metadata', ['email'], unique=1)
    op.drop_column('image_metadata', 'style')
    op.drop_column('image_metadata', 'price')
    op.drop_column('image_metadata', 'pattern')
    op.drop_column('image_metadata', 'material')
    op.drop_column('image_metadata', 'image_path_short')
    op.drop_column('image_metadata', 'image_path_full')
    op.drop_column('image_metadata', 'image')
    op.drop_column('image_metadata', 'fit')
    op.drop_column('image_metadata', 'description')
    op.drop_column('image_metadata', 'clothing')
    op.drop_column('image_metadata', 'brand')
    # ### end Alembic commands ###
