"""empty message

Revision ID: ea52ab74d0a1
Revises: cd23b441fa1d
Create Date: 2021-03-13 09:25:33.597325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea52ab74d0a1'
down_revision = 'cd23b441fa1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_image', sa.String(length=120), nullable=True),
    sa.Column('similar_image', sa.String(length=120), nullable=True),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('price', sa.Float(precision=64), nullable=True),
    sa.Column('image_path_short', sa.String(length=120), nullable=True),
    sa.Column('clothing', sa.String(length=120), nullable=True),
    sa.Column('material', sa.String(length=120), nullable=True),
    sa.Column('pattern', sa.String(length=120), nullable=True),
    sa.Column('fit', sa.String(length=120), nullable=True),
    sa.Column('style', sa.String(length=120), nullable=True),
    sa.Column('image_path_full', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_image'),
    sa.UniqueConstraint('image_path_full'),
    sa.UniqueConstraint('similar_image')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_metadata')
    # ### end Alembic commands ###
